//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flashApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public appUser()
        {
            this.postResponses = new HashSet<postResponse>();
            this.userFollowers = new HashSet<userFollower>();
            this.userFollowers1 = new HashSet<userFollower>();
            this.userPosts = new HashSet<userPost>();
        }
    
        public string name { get; set; }
        public string userName { get; set; }
        public string pwd { get; set; }
        public System.DateTime dob { get; set; }
        public string mailID { get; set; }
        public string profilePic { get; set; }
        public string bio { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<postResponse> postResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userFollower> userFollowers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userFollower> userFollowers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPost> userPosts { get; set; }
    }
}
