//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flashApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smappEntities : DbContext
    {
        public smappEntities()
            : base("name=smappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appUser> appUsers { get; set; }
        public virtual DbSet<postResponse> postResponses { get; set; }
        public virtual DbSet<userFollower> userFollowers { get; set; }
        public virtual DbSet<userPost> userPosts { get; set; }
    }
}
