//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flashApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postResponse
    {
        public long postId { get; set; }
        public string userName { get; set; }
        public string comment { get; set; }
        public Nullable<bool> pLike { get; set; }
        public Nullable<bool> readStatus { get; set; }
    
        public virtual appUser appUser { get; set; }
        public virtual userPost userPost { get; set; }
    }
}
