//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flashApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userFollower
    {
        public string userName { get; set; }
        public string followerUN { get; set; }
        public Nullable<int> prox { get; set; }
    
        public virtual appUser appUser { get; set; }
        public virtual appUser appUser1 { get; set; }
    }
}
